language: python
python:
  # - 2.7
  - "2.7_with_system_site_packages"
  # - 3.2
  - "3.2_with_system_site_packages"
  # - 3.3
  # - 3.4
  # - pypy
# virtualenv:
  # system_site_packages: true
addons:
  apt:
    packages:
      - python-dbus
      - python3-dbus
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-gi python3-gi
install:
  - pip install --upgrade pip
  - pip install pep8
  - pip install python-dbusmock
before_script:
  - "pep8 bluezero"
  - "pep8 examples"
  - "pep8 tests"
script:
  - python -m unittest discover