language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-gi python3-gi python-dbus python3-dbus
install:
  - pip install --upgrade pip
  - pip install pep8
  - pip install python-dbusmock
before_script:
  - "pep8 bluezero"
script:
  - python -m unittest discover