language: python
sudo: false

# look at https://github.com/pypa/pip for examples?
# https://docs.travis-ci.com/user/multi-os/
python:
  # - 2.7
  - "2.7_with_system_site_packages"
  # - 3.2
  # - "3.2_with_system_site_packages"
  # - 3.3
  # - "3.3_with_system_site_packages"
  # - 3.4
  # - pypy
# virtualenv:
  # system_site_packages: true
# matrix:
  # include:
    # - python: 2.7
    #   env: PYTHONPATH="$PYTHONPATH:/usr/lib/python2.7/dist-packages"
    # - python: 3.3
    #   env: PYTHONPATH="$PYTHONPATH:/usr/lib/python3/dist-packages"
addons:
  apt:
    packages:
      - python-dbus
      - python3-dbus
      - python-gi
      - python3-gi
# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -qq python-gi
#   - sudo apt-get install -qq python3-gi
#   - sudo apt-get install -qq python-dbus
#   - sudo apt-get install -qq python3-dbus
install:
  - pip install --upgrade pip
  - pip install pep8
  - pip install python-dbusmock
before_script:
  # - .travis/setup.sh
  # - echo "Travis Python Version ***********"
  # - echo $TRAVIS_PYTHON_VERSION
  # - echo $PYTHONPATH
  - "pep8 bluezero"
  - "pep8 examples"
  - "pep8 tests"
script:
  - python -m unittest discover
